---
# handlers file for ansible-guacamole
- name: Guacamole post-install | Daemon-reload (reload systemctl)
  systemd:
    daemon_reload: yes
- name: Tomcat post-install | Restart guacd
  service:
    name: guacd
    state: restarted
  become: true
