---
- name: Tomcat post-install | Daemon-reload (reload systemctl)
  systemd:
    daemon_reload: yes
- name: Tomcat post-install |Enable and start Tomcat as a service
  systemd: 
    name: tomcat.service
    enabled: yes
    masked: no
    state: started
